[project]
name = "llm-balancer"
version = "0.1.0"
description = "A LLM load balancer."
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
requires-python = ">=3.12"
dependencies = [
    "transformers>=4.57.1",
    "fastapi",
    "numpy",
    "uvicorn",
    "openai>=2.8.0"
]

[project.optional-dependencies]
vllm = [
    "vllm==0.11.0",
    "msgspec",
    "zmq"
]

lmcache = [
    "lmcache>=0.3.7"
]

[tool.setuptools.packages.find]
include = ["llm_balancer*", "llm_balancer_vllm_plugin*"]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.entry-points."vllm.general_plugins"]
vllm_balancer_vllm_plugin = "llm_balancer_vllm_plugin:monkey_patch"

[project.scripts]
llm-balancer-http = "llm_balancer.api.http.app:main"
