[project]
name = "llm-balancer"
version = "0.1.0"
description = "A LLM load balancer."
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    "transformers",
    "fastapi",
    "numpy",
    "uvicorn"
]

[project.optional-dependencies]
vllm = [
    "vllm",
    "msgspec",
    "zmq"
]

lmcache = [
    "lmcache"
]

[tool.setuptools.packages.find]
include = ["llm_balancer*", "llm_balancer_vllm_plugin*"]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.entry-points."vllm.general_plugins"]
vllm_balancer_vllm_plugin = "llm_balancer_vllm_plugin:monkey_patch"

[project.scripts]
llm-balancer-http = "llm_balancer.api.http.app:main"
